import yaml
import csv
import re


def liftr(file_path):
    csv_file = open("spreadsheet.csv", "w+")
    csvwriter = csv.writer(csv_file)

    with open(file_path, "r") as yaml_file:
        program = yaml.load(yaml_file)

    units = program.get("config").get("units", "lbs")

    csvwriter.writerow(["Generated by Liftr"])
    csvwriter.writerow(["Developed by NAEK (https://github.com/naek2k/liftr)"])
    csvwriter.writerow([])

    csvwriter.writerow(["Maxes"])
    for lift, weight in program.get("maxes").items():
        csvwriter.writerow([lift, weight, units])
    csvwriter.writerow([])

    for week, days in program.get("program").items():
        csvwriter.writerow([week])
        csvwriter.writerow([])
        for day, exercises in days.items():
            csvwriter.writerow([day])
            csvwriter.writerow([])
            for exercise, options in exercises.items():
                for i in range(options.get("sets")):
                    weight = options.get("weight")

                    percent_match = re.search(r"(\d+)(%)", str(weight))
                    if percent_match:
                        weight = (
                            program.get("maxes").get(exercise)
                            * int(percent_match.groups()[0])
                            / 100
                        )

                    if not i:
                        csvwriter.writerow(
                            [exercise, options.get("reps"), weight, units]
                        )
                    else:
                        csvwriter.writerow(["", options.get("reps"), weight, units])
            csvwriter.writerow([])

    csv_file.close()


if __name__ == "__main__":
    liftr("program.yaml")